# Generated by Django 5.2 on 2025-05-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('classID', models.CharField(max_length=100, unique=True)),
                ('schoolYear', models.IntegerField()),
                ('accessCode', models.CharField(max_length=8, unique=True)),
                ('semester', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('userID', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('birthDate', models.DateField()),
                ('gender', models.CharField(max_length=1)),
                ('schoolYear', models.IntegerField()),
                ('recommendations', models.CharField(default='None', max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('userID', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('birthDate', models.DateField()),
                ('schoolYear', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('accessCode', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
