# Generated by Django 5.2 on 2025-05-02 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseID', models.CharField(max_length=100, unique=True)),
                ('schoolYear', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='schoolYear',
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=models.EmailField(max_length=254, unique=True), max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(default=models.EmailField(max_length=254, unique=True), max_length=100),
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interestID', models.CharField(max_length=100, unique=True)),
                ('interest', models.CharField(max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='CourseInterestWeights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.interests')),
            ],
        ),
    ]
