# Generated by Django 5.2 on 2025-05-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_course_remove_teacher_schoolyear_student_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='interests',
            field=models.ManyToManyField(through='api.CourseInterestWeights', to='api.interests'),
        ),
    ]
