# Generated by Django 5.2 on 2025-05-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_course_interests'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyHabits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weeklyStudyHours', models.IntegerField()),
                ('weeklyStudySessions', models.IntegerField()),
                ('sessionLength', models.FloatField()),
                ('contentType', models.JSONField(default=list)),
            ],
        ),
        migrations.RemoveField(
            model_name='interests',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='interests',
            field=models.ManyToManyField(to='api.interests'),
        ),
        migrations.AddField(
            model_name='student',
            name='wifiAtHome',
            field=models.BooleanField(default=True),
        ),
    ]
