# Generated by Django 5.2 on 2025-05-02 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_studyhabits_remove_interests_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyhabits',
            name='students',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.student'),
        ),
    ]
