# Generated by Django 5.2 on 2025-05-02 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_class_students_class_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentID', models.CharField(max_length=100, unique=True)),
                ('subject', models.CharField(max_length=100)),
                ('length', models.FloatField()),
                ('timeSpent', models.FloatField()),
                ('dateCreated', models.DateField(auto_now_add=True)),
                ('dateModified', models.DateField(auto_now=True)),
                ('contentType', models.CharField(default='Quizz', max_length=100)),
                ('contentURL', models.URLField()),
                ('contentDescription', models.TextField()),
                ('questions', models.JSONField(default=list)),
                ('correctAnswers', models.JSONField(default=list)),
                ('publisherTeacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.teacher')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuizzInteractions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('timeSpent', models.FloatField()),
                ('score', models.FloatField()),
                ('studentAnswers', models.JSONField(default=list)),
                ('questionTimes', models.JSONField(default=list)),
                ('questionCertainty', models.JSONField(default=list)),
                ('questionAttempts', models.JSONField(default=list)),
                ('content', models.ForeignKey(default='Quizz', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.quizz')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
        ),
        migrations.AddField(
            model_name='quizz',
            name='students',
            field=models.ManyToManyField(through='api.QuizzInteractions', to='api.student'),
        ),
    ]
