# Generated by Django 5.2 on 2025-05-02 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_quizz_quizzinteractions_quizz_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizzinteractions',
            name='timeSpent',
        ),
    ]
