services: 
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 4000:4000
      - 9229:9229
    volumes:
      - ./backend:/api
      - /backend:/efidu
    command: 'python manage.py runserver'