services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 4000:4000
      - 9229:9229
    volumes:
      - ./backend:/app
    working_dir: /app
    environment:
      - DJANGO_SETTINGS_MODULE=efidu.settings
    command: ['python', 'manage.py', 'runserver', '0.0.0.0:4000']

  frontend:
    build:
      context: ./frontend/efidu-fe
      dockerfile: Dockerfile
    ports:
      - 19000:19000
      - 19001:19001
      - 19002:19002
    volumes:
      - ./frontend/efidu-fe:/app
      - /app/node_modules
    environment:
      - RCT_METRO_PORT=19000
      - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.56.1
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    working_dir: /app
    command: 'npx expo start'
