services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 4000:4000
      - 9229:9229
    volumes:
      - ./backend:/app
    working_dir: /app
    environment:
      - DJANGO_SETTINGS_MODULE=efidu.settings
    command: ['python', 'manage.py', 'runserver', '0.0.0.0:4000']

  frontend:
    build:
      context: ./frontend/efidu-fe
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 9228:9228
    volumes:
      - ./efidu-fe:/app
      - /app/node_modules
    command: 'npx expo start'
