services:
  backend:
    depends_on:
      - db_efidu
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 4000:4000
      - 9229:9229
    volumes:
      - ./backend:/app
    working_dir: /app
    environment:
      - DJANGO_SETTINGS_MODULE=efidu.settings
    command: ['sh', '-c', 'python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:4000']
    env_file:
      - .env

  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: ['sh', '-c', 'npm install && npm run dev']
    env_file:
      - .env
  db_efidu:
    container_name: db_efidu
    image: postgres:17.1-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: db
volumes:
  pgdata: {}
